import React, { useState } from "react";
import { Check, Calculator, ShoppingCart } from "lucide-react";
import { PLANS, ALACARTE_FEATURES } from "@/lib/mockData";

export const ViewSubscription: React.FC<{ addNotification: (t: 'success' | 'error', m: string) => void }> = ({ addNotification }) => {
    const [customFeatures, setCustomFeatures] = useState<Record<string, boolean>>({});
    const toggleFeature = (id: string) => setCustomFeatures(prev => ({ ...prev, [id]: !prev[id] }));
    const calculateTotal = () => ALACARTE_FEATURES.reduce((acc, f) => customFeatures[f.id] ? acc + f.price : acc, 0);
    const formatPrice = (p: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(p);

    return (
        <div className="space-y-12 pb-24 animate-in fade-in duration-500">
            <div className="text-center max-w-3xl mx-auto"><h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">Pilih Paket Berlangganan</h2><p className="text-muted text-sm">Mulai gratis atau buat paket custom sesuai kebutuhan bisnis Anda.</p></div>
            <div id="sub-plans" className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-6">{PLANS.map((plan, idx) => (<div key={idx} className={`relative bg-card-bg border ${plan.color} rounded-2xl p-6 flex flex-col transition-all hover:-translate-y-2 hover:shadow-2xl hover:shadow-primary/10 group shadow-sm`}>{plan.tag && <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-primary text-white text-[10px] font-bold px-3 py-1 rounded-full shadow-lg">{plan.tag}</div>}<div className="mb-6"><h3 className="text-lg font-bold text-foreground group-hover:text-primary transition-colors">{plan.name}</h3><div className="flex items-end gap-1"><span className="text-2xl font-bold text-foreground">{plan.price}</span><span className="text-xs text-muted mb-1">{plan.period}</span></div></div><div className="flex-1 space-y-3 mb-8">{plan.features.map((f, i) => (<div key={i} className="flex gap-2 text-xs text-muted-light"><Check size={14} className="text-tertiary shrink-0" />{f}</div>))}</div><button onClick={() => addNotification('success', `Paket ${plan.name} dipilih`)} className={`w-full py-2.5 rounded-lg text-sm font-bold transition-all shadow-lg ${plan.highlight ? 'bg-primary hover:bg-primary-dark text-white' : 'bg-surface text-foreground border border-border hover:bg-surface-hover'}`}>Pilih</button></div>))}</div>
            <div id="sub-calculator" className="bg-card-bg border border-border rounded-3xl overflow-hidden grid grid-cols-1 lg:grid-cols-3 shadow-2xl transition-colors"><div className="lg:col-span-2 p-6 md:p-8 border-b lg:border-b-0 lg:border-r border-border"><div className="flex items-center gap-3 mb-6"><div className="p-3 bg-blue-100 dark:bg-blue-500/20 text-blue-600 dark:text-blue-400 rounded-xl"><Calculator size={24} /></div><div><h3 className="text-xl font-bold text-foreground">Metode A La Carte</h3><p className="text-muted text-xs">Bayar fitur yang Anda butuhkan saja.</p></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{ALACARTE_FEATURES.map((feat) => (<div key={feat.id} onClick={() => toggleFeature(feat.id)} className={`p-4 rounded-xl border cursor-pointer flex items-center gap-3 transition-all ${customFeatures[feat.id] ? 'bg-primary/5 border-primary shadow-lg' : 'bg-surface border-border hover:bg-surface-hover'}`}><div className={`w-5 h-5 rounded border flex items-center justify-center shrink-0 transition-colors ${customFeatures[feat.id] ? 'bg-primary border-primary' : 'border-muted-light'}`}>{customFeatures[feat.id] && <Check size={12} className="text-white" />}</div><div><h4 className="text-sm font-bold text-foreground">{feat.name}</h4><span className="text-xs text-primary">{formatPrice(feat.price)}</span></div></div>))}</div></div><div className="p-6 md:p-8 bg-surface-hover flex flex-col justify-between h-full"><div><h4 className="font-bold text-foreground mb-4 flex items-center gap-2"><ShoppingCart size={18} /> Ringkasan</h4><div className="space-y-2 mb-4">{Object.keys(customFeatures).length === 0 ? <p className="text-xs text-muted italic text-center py-4">Belum ada fitur dipilih.</p> : ALACARTE_FEATURES.filter(f => customFeatures[f.id]).map(f => <div key={f.id} className="flex justify-between text-xs text-muted-light animate-in slide-in-from-right"><span>{f.name}</span><span>{formatPrice(f.price)}</span></div>)}</div></div><div><div className="flex justify-between items-end mb-4"><span className="text-muted text-sm">Total Bulanan</span><span className="text-2xl font-bold text-foreground">{formatPrice(calculateTotal())}</span></div><button disabled={calculateTotal() === 0} onClick={() => addNotification('success', 'Paket Custom aktif!')} className="w-full py-3 bg-primary hover:bg-primary-dark text-white font-bold rounded-xl disabled:opacity-50 transition-colors shadow-lg">Langganan Sekarang</button></div></div></div>
        </div>
    );
};
